###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

#bakerymanager-mailhog:
  #image: phpdockerio/mailhog:latest
  #container_name: bakerymanager-mailhog
  #ports:
    #- "8125:8025"

bakerymanager-mysql:
  image: mysql:5.7
  container_name: bakerymanager-mysql
  volumes:
      - ../mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
  ports:
    - "8106:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}

bakerymanager-nginx:
  image: nginx
  container_name: bakerymanager-nginx
  volumes:
      - ./src:/var/www/bakeryManager
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8180:80"
  links:
   - bakerymanager-php-fpm

bakerymanager-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: bakerymanager-php-fpm
  volumes:
    - ./src:/var/www/bakeryManager
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    #- bakerymanager-mailhog
    - bakerymanager-mysql
